apiVersion: run.tanzu.vmware.com/v1alpha1      #TKGS API endpoint
kind: TanzuKubernetesCluster                   #required parameter
metadata:
  name: impactorlab                         #cluster name, user defined
  namespace: impactor                   #vsphere namespace
spec:
  distribution:
    version: v1.20.7                             #Resolves to latest TKR 1.20
  topology:
    controlPlane:
      count: 1                                 #number of control plane nodes
      class: impactor                #vmclass for control plane nodes
      storageClass: vsan-default-storage-policy          #storageclass for control plane
    workers:
      count: 3                                 #number of worker nodes
      class: napp-advanced                #vmclass for worker nodes
      storageClass: vsan-default-storage-policy         #storageclass for worker nodes